services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3270:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      PUID: $PUID
      PGID: $PGID
    restart: unless-stopped